# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f9639d646947c733e73250e59f6cc2e9c980f00ddc3d2d79851ef65eae70d65c06bae3a24fd2662421d659d1ac89f9ed5f28d1d36cedd6c90e30c942921301f

test:
  secret_key_base: ed632ce0d0572f60c25afcc1825522b68757cb2cd396eb7fbdf75cf366c3a21af6c550bb34a4b781c7d33b02854537f877bc32262d780e96d1f09b46def91f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
